from __future__ import annotations

from pathlib import Path
from typing import Literal

from fastapi import APIRouter, File, HTTPException, UploadFile
from pydantic import BaseModel, Field

from app.db.models import Project, ProjectArtifact, ProjectIndexEntry
from app.db.session import SessionLocal
from app.services.parser import parse_file
from app.services.persistence import load_state_snapshot, save_state_snapshot
from app.services.storage import upload_local_file
from app.services.workflow import (
    append_parsed_document,
    approve_and_export,
    approve_architecture,
    approve_sprint,
    get_project_state,
    init_project_state,
    resume_discovery,
    run_architecture_stage,
    run_sprint_stage,
    run_stage1_and_discovery,
)
from app.shared.event_bus import event_bus


projects_router = APIRouter(prefix="/projects", tags=["projects"])


def _persist_index_metadata(project_id: str, version: int, events: list[dict]) -> None:
    """Save index metadata rows generated by graph events."""
    with SessionLocal() as db:
        for event in events:
            event_type = event.get("type")
            payload = event.get("payload", {})
            if event_type not in {"working_index_created", "approved_index_created"}:
                continue
            index_kind = "working" if event_type == "working_index_created" else "approved"
            index_path = payload.get("index_path")
            if not index_path:
                continue
            db.add(
                ProjectIndexEntry(
                    project_id=project_id,
                    version=version,
                    index_kind=index_kind,
                    index_path=index_path,
                )
            )
        db.commit()


def _persist_artifact_metadata(project_id: str, version: int, updated: dict) -> None:
    """Save exported artifact metadata rows for audit/history."""
    artifact_rows = [
        ("pdf", updated.get("final_doc_pdf_s3_key")),
        ("docx", updated.get("final_doc_docx_s3_key")),
    ]
    with SessionLocal() as db:
        for artifact_type, artifact_path in artifact_rows:
            if not artifact_path:
                continue
            db.add(
                ProjectArtifact(
                    project_id=project_id,
                    version=version,
                    artifact_type=artifact_type,
                    artifact_path=artifact_path,
                )
            )
        db.commit()


class CreateProjectRequest(BaseModel):
    name: str = Field(min_length=1, max_length=255)
    additional_context: str = ""


class AnswerRequest(BaseModel):
    answer: str | None = None
    status: Literal["answered", "deferred", "na", "unknown"] = "answered"
    selected_option_index: int | None = None
    terminate: bool = False


class ApproveRequest(BaseModel):
    user_edits_payload: dict | None = None


class SprintApproveRequest(BaseModel):
    sprint_notes: str | None = None
    user_edits_payload: dict | None = None


@projects_router.post("")
async def create_project(payload: CreateProjectRequest) -> dict:
    """Create a project row and initialize runtime graph state."""
    with SessionLocal() as db:
        project = Project(name=payload.name, status="draft")
        db.add(project)
        db.commit()
        db.refresh(project)

    state = init_project_state(
        project_id=project.id,
        name=payload.name,
        additional_context=payload.additional_context,
    )
    snapshot_path = save_state_snapshot(project.id, state)
    return {
        "project_id": project.id,
        "status": project.status,
        "snapshot": snapshot_path,
    }


@projects_router.post("/{project_id}/files")
async def upload_project_file(project_id: str, file: UploadFile = File(...)) -> dict:
    """Upload one file, parse it, and attach parsed sections to runtime state."""
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")

    tmp_dir = Path("/tmp") / "bra_uploads"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    local_file = tmp_dir / file.filename
    local_file.write_bytes(await file.read())

    object_key = f"{project_id}/{file.filename}"
    storage_key = upload_local_file(local_file, object_key)

    sections = parse_file(local_file)
    parsed_document = {
        "file_name": file.filename,
        "file_type": file.content_type or "application/octet-stream",
        "s3_key": storage_key,
        "sections": sections,
    }
    updated = append_parsed_document(project_id, parsed_document, file.filename)
    save_state_snapshot(project_id, updated)

    return {
        "project_id": project_id,
        "file_name": file.filename,
        "sections": len(sections),
        "storage_key": storage_key,
    }


@projects_router.post("/{project_id}/run")
async def run_project(project_id: str) -> dict:
    """Run Stage-1 and Stage-2 flow for a project."""
    state = get_project_state(project_id)
    if state is None:
        persisted = load_state_snapshot(project_id)
        if persisted is None:
            raise HTTPException(status_code=404, detail="Project state not found")
        raise HTTPException(
            status_code=409,
            detail="Project exists only as snapshot; recreate runtime or restart from create endpoint.",
        )

    updated = run_stage1_and_discovery(project_id)
    save_state_snapshot(project_id, updated)
    _persist_index_metadata(project_id, updated.get("version", 1), updated.get("streaming_events", []))

    with SessionLocal() as db:
        project = db.get(Project, project_id)
        if project is not None:
            project.status = "in_review"
            db.add(project)
            db.commit()

    return {
        "project_id": project_id,
        "score": updated.get("score"),
        "current_question": updated.get("current_question"),
        "final_doc_markdown": updated.get("final_doc_markdown"),
    }


@projects_router.post("/{project_id}/discovery/answer")
async def answer_discovery(project_id: str, payload: AnswerRequest) -> dict:
    """Resume discovery after user answers a question."""
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")

    updated = resume_discovery(
        project_id=project_id,
        answer=payload.answer,
        status=payload.status,
        selected_option_index=payload.selected_option_index,
        terminate=payload.terminate,
    )
    save_state_snapshot(project_id, updated)

    return {
        "project_id": project_id,
        "current_question": updated.get("current_question"),
        "qa_history_count": len(updated.get("qa_history", [])),
        "final_doc_markdown": updated.get("final_doc_markdown"),
    }


@projects_router.post("/{project_id}/approve")
async def approve_project(project_id: str, payload: ApproveRequest) -> dict:
    """Approve project output and generate final artifacts."""
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")

    updated = approve_and_export(project_id, payload.user_edits_payload)
    save_state_snapshot(project_id, updated)
    _persist_index_metadata(project_id, updated.get("version", 1), updated.get("streaming_events", []))
    _persist_artifact_metadata(project_id, updated.get("version", 1), updated)

    with SessionLocal() as db:
        project = db.get(Project, project_id)
        if project is not None:
            project.status = "approved"
            db.add(project)
            db.commit()

    return {
        "project_id": project_id,
        "status": "approved",
        "final_doc_pdf_s3_key": updated.get("final_doc_pdf_s3_key"),
        "final_doc_docx_s3_key": updated.get("final_doc_docx_s3_key"),
    }


@projects_router.get("/{project_id}")
async def get_project(project_id: str) -> dict:
    """Read full project runtime/snapshot state for debugging UI."""
    state = get_project_state(project_id)
    if state is None:
        persisted = load_state_snapshot(project_id)
        if persisted is None:
            raise HTTPException(status_code=404, detail="Project not found")
        return {"project_id": project_id, "state": persisted, "source": "snapshot"}
    return {"project_id": project_id, "state": state, "source": "runtime"}


@projects_router.get("/{project_id}/events")
async def get_project_events(project_id: str) -> dict:
    """Return project event backlog for polling clients."""
    return {
        "project_id": project_id,
        "events": event_bus.backlog(project_id),
    }


# ──────────────────────────────────────────────────────────────────────────────
# Stage 3 — Architecture endpoints
# ──────────────────────────────────────────────────────────────────────────────

@projects_router.post(
    "/{project_id}/architecture/run",
    tags=["architecture"],
    summary="Run Architecture Agent (mocked)",
)
async def run_architecture(project_id: str) -> dict:
    """
    Trigger Stage-3 Architecture Agent.

    Generates mocked Mermaid + PlantUML diagrams based on the approved
    Stage-1 analyser output.  Returns the full `architecture_output`.

    **Note:** The Architecture Agent is currently using mocked data
    (`is_mocked: true`). Replace with the real agent when ready.
    """
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")
    if not state.get("analyser_output"):
        raise HTTPException(
            status_code=409,
            detail="Stage 1 (Analyser) must be completed before running Architecture stage.",
        )

    updated = run_architecture_stage(project_id)
    save_state_snapshot(project_id, updated)

    arch = updated.get("architecture_output") or {}
    return {
        "project_id": project_id,
        "architecture_output": arch,
        "diagram_count": len(arch.get("diagrams", [])),
        "is_mocked": arch.get("is_mocked", True),
    }


@projects_router.get(
    "/{project_id}/architecture",
    tags=["architecture"],
    summary="Get Architecture output",
)
async def get_architecture(project_id: str) -> dict:
    """
    Return the current `architecture_output` for the project.

    Includes all diagram DSL strings (Mermaid / PlantUML) and tech stack notes.
    Returns 404 if the Architecture stage has not been run yet.
    """
    state = get_project_state(project_id)
    if state is None:
        persisted = load_state_snapshot(project_id)
        if persisted is None:
            raise HTTPException(status_code=404, detail="Project not found")
        state = persisted

    arch = state.get("architecture_output")
    if not arch:
        raise HTTPException(
            status_code=404,
            detail="Architecture stage has not been run yet. Call POST /architecture/run first.",
        )
    return {
        "project_id": project_id,
        "architecture_output": arch,
        "review_3_status": state.get("review_3_status", "pending"),
    }


@projects_router.post(
    "/{project_id}/architecture/approve",
    tags=["architecture"],
    summary="Approve Architecture output",
)
async def approve_architecture_endpoint(project_id: str, payload: ApproveRequest) -> dict:
    """
    Approve Stage-3 architecture diagrams and advance pipeline to Sprint stage.

    Optional `user_edits_payload` is stored for audit purposes.
    """
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")
    if not state.get("architecture_output"):
        raise HTTPException(
            status_code=409,
            detail="No architecture output to approve. Run POST /architecture/run first.",
        )

    updated = approve_architecture(project_id, payload.user_edits_payload)
    save_state_snapshot(project_id, updated)

    return {
        "project_id": project_id,
        "review_3_status": updated.get("review_3_status"),
        "message": "Architecture approved. You can now run the Sprint stage.",
    }


# ──────────────────────────────────────────────────────────────────────────────
# Stage 4 — Sprint Planning endpoints
# ──────────────────────────────────────────────────────────────────────────────

@projects_router.post(
    "/{project_id}/sprint/run",
    tags=["sprint"],
    summary="Run Sprint Planning Agent",
)
async def run_sprint(project_id: str) -> dict:
    """
    Trigger Stage-4 Sprint Planning Agent.

    **Inputs (from state):**
    - `analyser_output` — Stage 1 functional requirements, risks, team (required)
    - `architecture_output` — Stage 3 diagrams + tech notes (auto-mocked if missing)

    **Output:**
    - `sprint_plan` with full sprint breakdown, story points, man-hours, MVP cut-off,
      team composition, tech stack, and risk register.

    The sprint plan is deterministically generated from requirements and optionally
    improved by the configured LLM (OpenAI / Anthropic).
    """
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")
    if not state.get("analyser_output"):
        raise HTTPException(
            status_code=409,
            detail="Stage 1 (Analyser) must be completed before running Sprint stage.",
        )

    updated = run_sprint_stage(project_id)
    save_state_snapshot(project_id, updated)

    plan = updated.get("sprint_plan") or {}
    return {
        "project_id": project_id,
        "sprint_plan": plan,
        "summary": {
            "total_sprints": plan.get("total_sprints"),
            "total_story_points": plan.get("total_story_points"),
            "total_man_hours": plan.get("total_man_hours"),
            "mvp_cutoff_sprint": plan.get("mvp_cutoff_sprint"),
            "sprint_duration_weeks": plan.get("sprint_duration_weeks"),
        },
    }


@projects_router.get(
    "/{project_id}/sprint",
    tags=["sprint"],
    summary="Get Sprint Plan",
)
async def get_sprint(project_id: str) -> dict:
    """
    Return the current `sprint_plan` for the project.

    Includes all sprint objects, stories, team composition, tech stack,
    and risk register.  Returns 404 if Sprint stage has not been run yet.
    """
    state = get_project_state(project_id)
    if state is None:
        persisted = load_state_snapshot(project_id)
        if persisted is None:
            raise HTTPException(status_code=404, detail="Project not found")
        state = persisted

    plan = state.get("sprint_plan")
    if not plan:
        raise HTTPException(
            status_code=404,
            detail="Sprint stage has not been run yet. Call POST /sprint/run first.",
        )
    return {
        "project_id": project_id,
        "sprint_plan": plan,
        "review_4_status": state.get("review_4_status", "pending"),
    }


@projects_router.post(
    "/{project_id}/sprint/approve",
    tags=["sprint"],
    summary="Approve Sprint Plan and finalize project",
)
async def approve_sprint_endpoint(project_id: str, payload: SprintApproveRequest) -> dict:
    """
    Approve Stage-4 sprint plan — this **finalizes the project** and exports artifacts.

    Optional `sprint_notes` are appended to the sprint plan for audit.
    After approval:
    - The RAG approved index is saved.
    - PDF + DOCX artifacts are generated and stored.
    - Project status is set to `approved`.
    """
    state = get_project_state(project_id)
    if state is None:
        raise HTTPException(status_code=404, detail="Project runtime state not found")
    if not state.get("sprint_plan"):
        raise HTTPException(
            status_code=409,
            detail="No sprint plan to approve. Run POST /sprint/run first.",
        )

    # Merge sprint_notes into user_edits_payload
    edits = payload.user_edits_payload or {}
    if payload.sprint_notes:
        edits["sprint_notes"] = payload.sprint_notes

    updated = approve_sprint(project_id, edits if edits else None)
    save_state_snapshot(project_id, updated)
    _persist_index_metadata(project_id, updated.get("version", 1), updated.get("streaming_events", []))
    _persist_artifact_metadata(project_id, updated.get("version", 1), updated)

    with SessionLocal() as db:
        project = db.get(Project, project_id)
        if project is not None:
            project.status = "approved"
            db.add(project)
            db.commit()

    return {
        "project_id": project_id,
        "status": "approved",
        "review_4_status": updated.get("review_4_status"),
        "final_doc_pdf_s3_key": updated.get("final_doc_pdf_s3_key"),
        "final_doc_docx_s3_key": updated.get("final_doc_docx_s3_key"),
        "sprint_plan_summary": {
            "total_sprints": (updated.get("sprint_plan") or {}).get("total_sprints"),
            "total_story_points": (updated.get("sprint_plan") or {}).get("total_story_points"),
            "mvp_cutoff_sprint": (updated.get("sprint_plan") or {}).get("mvp_cutoff_sprint"),
        },
    }

