"""
app.main
========
FastAPI application factory. Single entrypoint referenced by:
    uvicorn app.main:app --reload

Responsibilities:
    * configure CORS
    * include the versioned API router (`/api`)
    * register the WebSocket router (`/ws/...`)
    * wire startup / shutdown lifecycle hooks

When adding a new *resource* (e.g. `tags`), create `app/api/v1/tags.py` and
register its router inside `app/api/v1/router.py` — do NOT edit this file.
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.agents.graph import get_graph
from app.api.v1.router import api_router
from app.api.v1.websocket import ws_router
from app.core.config import settings
from app.core.logging import configure_logging
from app.db.base import Base
from app.db.session import engine

log = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup / shutdown lifecycle.

    Startup:
        1. configure application logging
        2. ensure local directories exist (uploads/, exports/)
        3. create all SQLAlchemy tables (SQLite auto-creates the file)
        4. compile the LangGraph `StateGraph` once and cache it on `app.state`
        5. log a summary so juniors know what loaded successfully

    Shutdown:
        * dispose the SQLAlchemy engine (closes the connection pool cleanly)
    """
    # 1. logging
    configure_logging()
    log.info("BRA Tool starting (env=%s, debug=%s)", settings.app_env, settings.app_debug)

    # 2. local storage directories
    settings.upload_dir.mkdir(parents=True, exist_ok=True)
    settings.export_dir.mkdir(parents=True, exist_ok=True)
    log.info("Upload dir: %s", settings.upload_dir.resolve())
    log.info("Export dir: %s", settings.export_dir.resolve())

    # 3. database — import models so metadata is populated, then create tables
    from app.db import models as _models  # noqa: F401  (registers ORM classes on Base.metadata)

    Base.metadata.create_all(bind=engine)
    log.info("Database ready at %s", settings.database_url)

    # 4. compile LangGraph once and expose to request handlers via app.state.graph
    app.state.graph = get_graph()
    log.info("LangGraph compiled with %d nodes", len(app.state.graph.nodes))

    yield

    # --- shutdown ---
    engine.dispose()
    log.info("BRA Tool stopped")


def create_app() -> FastAPI:
    """Create and configure FastAPI app instance."""
    app = FastAPI(
        title="BRA Tool API",
        version="0.1.0",
        description="AI-Powered Business Requirement Analysis Tool — see /docs.",
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins_list,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.include_router(api_router, prefix="/api")
    app.include_router(ws_router)  # mounted at /ws

    @app.get("/health", tags=["meta"])
    async def health() -> dict[str, str]:
        """Health endpoint used by local/dev checks."""
        return {"status": "ok"}

    return app


app = create_app()
